services:
  nginx:
    image: nginx:latest
    ports:
        - 81:80
    volumes:
      - ../:/web/mclogs
      - ./mclogs.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm
  php-fpm:
    build:
      context: .
      dockerfile: ./php.Dockerfile

    volumes:
      - ../:/web/mclogs
  mongo:
    image: mongo
    volumes:
      - mongo:/data/db
volumes:
  mongo: